### PR TITLE
Allow usage of namespace selection using wildcards

### PR DESCRIPTION
**Pull request by naxvog**
As discussed in https://github.com/pestphp/pest/discussions/1072 and https://github.com/pestphp/pest/discussions/728 this PR allows the usage of wildcards in namespace selection.

This is useful if a module/domain architecture needs to be tested.

Tried to include globstar too but unfortunately symfony finder, as far as I know, does not support it.

### CODE REVIEW

**Comment by jambonfarci** [comment]
Is this PR still active ?
There are no assignees.

**Comment by naxvog** [comment]
I will fix the merge conflicts in the coming days.
However, to be frank, after 7 months without any sign from the maintainers I am pessimistic about this finding its way into pest.

**Comment by clementbirkle** [comment]
@nunomaduro this PR seems useful for several users. Could you approve it please? Thank you in advance 🙏

**Comment by nunomaduro** [comment]
had to revert, because this test was failing:

```
arch()->expect('*')->toUseStrictTypes();
```

**Comment by naxvog** [comment]
> had to revert, because this test was failing:
> 
> ```
> arch()->expect('*')->toUseStrictTypes();
> ```

Sadly I could not find the test in question but added the one you mentioned anyway and the code passed the test.
However, I got the following failing test: Arch:base with the following message:

> Expecting 'Pest\Arch' to only use 'dd, dump, expect, test, Pest, PHPUnit\Architecture, Symfony\Component\Finder\Finder, PhpParser\Node, Whoops\Exception\Frame'. However, it also uses 'PhpParser\Node'.

That being said I corrected the Stan issue detected after the merge of #12 and opened #16 to reflect the change.

**Pull request merged**
